"""empty message

Revision ID: 72bd317ce1bd
Revises: bf15446d9590
Create Date: 2022-01-24 20:33:22.784080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bd317ce1bd'
down_revision = 'bf15446d9590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('apitoken', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'apitoken')
    # ### end Alembic commands ###
