"""empty message

Revision ID: bf15446d9590
Revises: 
Create Date: 2022-01-21 12:49:44.444392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf15446d9590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(length=150), nullable=False),
    sa.Column('program_cost', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program')
    # ### end Alembic commands ###
